language: python

dist: xenial

before_install:
  - sudo apt-get -y install texlive-xetex dvipng

env:
    global:
        - TEST_DIR=/tmp/circhic


matrix:
    include:
        - name: "Python 3.6"
          python: 3.6
          env: MATPLOTLIB_VERSION=3.0 NUMPY_VERSION=1.16 SCIPY_VERSION=0.19
        - name: "Python 3.8"
          python: 3.8
          env: MATPLOTLIB_VERSION=* NUMPY_VERSION=* SCIPY_VERSION=*

install:
    - source .build_tools/travis/install.sh

script:
    - bash .build_tools/travis/test_script.sh

deploy:
    provider: pages
    skip-cleanup: true
    # Set in the settings page of your repository, as a secure variable
    github-token: $GH_TOKEN  
    keep-history: true
    local-dir: doc/_build/html
    on:
        branch: master
